import json
from langchain_core.messages import HumanMessage, SystemMessage
from core.llm import get_llm
from core.database import get_supabase_client

def ask_helpdesk(user_id: str, message: str, page_context: str, history: list) -> str:
    """
    Handles a user's question to the Help Desk.
    Fetches the dynamic manual from the DB and responds using the LLM.
    Also logs the interaction for the learning engine.
    """
    llm = get_llm(temperature=0.3, max_tokens=1024)
    client = get_supabase_client()

    # 1. Fetch the dynamic "App Manual" rules
    rules_data = client.table("helpdesk_manual").select("*").execute()
    rules = rules_data.data if rules_data.data else []
    
    manual_str = ""
    for idx, rule in enumerate(rules):
        manual_str += f"{idx + 1}. [{rule['rule_category']}] {rule['rule_description']}\n"

    # 2. Construct the System Prompt
    system_prompt = f"""You are the Placement Copilot Help Desk Agent. Your job is to help users navigate the app and troubleshoot issues.
The user is currently on the '{page_context}' page. 

App Structure & Features:
- /career-plan: Shows the overall career roadmap generated by the Copilot.
- /dsa: Generates custom DSA plans and tracks DSA progress.
- /copilot: The main command center to chat with the AI and generate goals.
- /interview: For taking mock interviews and viewing feedback.
- /resume: For ATS scoring and resume analysis.
- /projects: Shows recommended projects based on skill gaps.
- /core-concepts: For learning Computer Science Fundamentals, System Design, etc.

Dynamic App Manual (Troubleshooting Rules):
{manual_str if manual_str else "No additional dynamic rules currently."}

Instructions:
- Keep your answers concise, friendly, and actionable.
- If the user asks a follow-up question, use the conversation history to understand the context (e.g., if you were just talking about mock interviews, assume a follow-up question is about mock interviews).
- If you don't know the answer, politely tell the user to contact support or try a different approach.
- Focus strictly on helping them use the Placement Copilot application. Do NOT write code or answer technical interview questions (tell them to use the Copilot or Interview tabs for that).
- CRITICAL: Output ONLY plain text. Do NOT use any Markdown formatting whatsoever. No bold (**), no italics (*), no lists (- or *). Just write simple, human-readable paragraphs separated by newlines.
"""

    messages = [SystemMessage(content=system_prompt)]
    
    # 3. Add History
    for msg in history:
        if msg.get("role") == "user":
            messages.append(HumanMessage(content=msg.get("content", "")))
        else:
            messages.append(SystemMessage(content=msg.get("content", ""))) # Simplification: using SystemMessage or AIMessage. We'll use AIMessage.
    
    from langchain_core.messages import AIMessage
    messages = [SystemMessage(content=system_prompt)]
    for msg in history:
        if msg.get("role") == "user":
            messages.append(HumanMessage(content=msg.get("content", "")))
        else:
            messages.append(AIMessage(content=msg.get("content", "")))
            
    # 4. Add current message
    messages.append(HumanMessage(content=message))

    # 5. Get response
    response = llm.invoke(messages)
    answer = response.content.strip()

    # 6. Log interaction for the self-learning engine
    try:
        client.table("helpdesk_logs").insert({
            "user_id": user_id,
            "question": message,
            "answer": answer,
            "page_context": page_context
        }).execute()
    except Exception as e:
        print(f"Failed to log helpdesk interaction: {e}")

    return answer
